# Generated by Django 4.1 on 2022-08-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_bank_ac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_ac',
            field=models.CharField(blank=True, default='*************XX', max_length=50),
        ),
    ]
