# Generated by Django 4.1 on 2022-08-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_bank_ac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=40)),
                ('otp', models.IntegerField()),
                ('token', models.CharField(max_length=65)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
